Fix RawString issue with Asciidoc and Markdown template extensions
quarkiverse/quarkus-qute-web pull request #149
Opened 2024-12-20 09:40 UTC by ia3andy

Fixes https://github.com/quarkiverse/quarkus-qute-web/issues/146

2024-12-20 09:42 UTC, jtama approved these changes
LGTM

2025-01-02 15:21 UTC, mkouba requested changes

2025-01-02 15:21 UTC, mkouba commented on asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java
> +import io.quarkus.qute.*;
Pls don't use wildcards for imports.

2025-01-02 15:21 UTC, mkouba commented on asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java
> +    static RawString convertToAsciidoc(String text, String ignoredName) {
How does it fix the problem with section params in #146? 

IIUIC this merely changes the behavior of `{text.asciidocToHtml}` in a way that it corresponds to `{text.asciidocToHtml.raw}`. Which is probably ok, unless someone wants to escape the result of conversion... which probably does not make a lot of sense, right?

2025-01-06 08:22 UTC, jtama commented on asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java
> +    static RawString convertToAsciidoc(String text, String ignoredName) {
What I was trying to achieve with an attribute was to prevent the the rendered content of beeing escaped. So if we have another to achieve the same it's fine. 
It may be still be of some use to be able to pass attributes to the section but this would be a good start.

2025-01-14 19:05 UTC, ia3andy commented on asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java
> +import io.quarkus.qute.*;
Will fix it tomoz

2025-01-14 19:06 UTC, ia3andy commented on asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java
> +    static RawString convertToAsciidoc(String text, String ignoredName) {
> How does it fix the problem with section params in #146?
> 
> IIUIC this merely changes the behavior of `{text.asciidocToHtml}` in a way that it corresponds to `{text.asciidocToHtml.raw}`. Which is probably ok, unless someone wants to escape the result of conversion... which probably does not make a lot of sense, right?

Yes that's why we make it the default behaviour, it doesn't make sense to use it escaped..

2025-01-15 09:35 UTC, mkouba commented on asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java
> +    static RawString convertToAsciidoc(String text, String ignoredName) {
> Which is probably ok, unless someone wants to escape the result of conversion... 

Actually, in that case a user can do something like `{text.asciidocToHtml.value}`.

2025-01-15 09:35 UTC, mkouba approved these changes

2025-01-15 09:35 UTC, merged